pub mod agent;
pub mod agent_policy;
pub mod agent_stream;
pub mod app_context;
pub mod cli;
pub mod confirmation;
pub mod custom_instructions;
pub mod git_ops;
pub mod grok_client;
pub mod image_input;
pub mod message_projection;
pub mod model_client;
pub mod onboarding;
pub mod protocol;
pub mod provider;
pub mod responses_adapter;
pub mod session_store;
pub mod settings;
pub mod slash_commands;
pub mod tool_catalog;
pub mod tool_context;
pub mod tools;
pub mod ui;

pub use ui::feedback as inline_feedback;
pub use ui::inline as inline_ui;
pub use ui::markdown as inline_markdown;
pub use ui::prompt as inline_prompt;
